name = "codebattles-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
GITHUB_OWNER = "bobrturbopetr-cyber"
GITHUB_REPO = "code-batles"

[env.production]
vars = { GITHUB_OWNER = "bobrturbopetr-cyber", GITHUB_REPO = "code-batles" }
